### ISSUE TITLE
Site not hosted on the root routing doesn't work k8s ingress

### ISSUE THREAD

**Issue by igloo12** [okta/okta-react#262]
### Describe the bug

I am trying to use the router with a K8s ingress controller hosted at path /my-app I am getting an error You need to enable JavaScript to run this app. 

If I remove the okta router and use the normal <switch><route> setup I can get the paths to works.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/default-backend: my-service
spec:
  tls:
    - secretName: tls-secret
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /my-app
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
```
If I change the above to use the root / it loads the app
```
...
paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
```
my nginx config is

```
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
```
package.json

```
...
  "homepage": ".",
```

### Reproduction Steps?

Setup okta router on k8s with ingress controller. Try to login

### SDK Versions

  System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 26.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /usr/local/bin/node
    npm: 9.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
